spring.application.name=Ev2_Monitoreo

# ==========================================
# SERVIDOR
# ==========================================
server.port=${PORT:8080}
server.address=0.0.0.0

# ==========================================
# POSTGRESQL
# ==========================================

#spring.datasource.url=jdbc:postgresql://localhost:5432/crud_productos_db
#spring.datasource.username=postgres
#spring.datasource.password=Luismiguel36
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA
# ==========================================

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false